In [1]:
import pandas as pd
import numpy as np
import pyarrow.parquet as pq
import pyarrow as pa
import os
import gc

# ─────────────────────────────────────────────
# Correct dataset path
# ─────────────────────────────────────────────

MASTER = "/kaggle/input/datasets/ayastudentkhoumari/fe-trade/algeria_trade_master_fe.parquet"

OUT = "/kaggle/working/algeria_trade_master_cleaned.parquet"

print("Input exists :", os.path.exists(MASTER))
print("Output path  :", OUT)

Input exists : True
Output path  : /kaggle/working/algeria_trade_master_cleaned.parquet

# Display Dataset Structure + Sample Rows

In [2]:
pf = pq.ParquetFile(MASTER)

print("=" * 60)
print("DATASET OVERVIEW")
print("=" * 60)

print(f"Total rows       : {pf.metadata.num_rows:,}")
print(f"Total columns    : {pf.metadata.num_columns}")
print(f"Row groups       : {pf.num_row_groups}")

print("\nCOLUMNS:")
for i, col in enumerate(pf.schema.names, 1):
    print(f"{i:2}. {col}")

# ─────────────────────────────────────────────
# Load ONLY small sample
# ─────────────────────────────────────────────

sample = pf.read_row_group(0).to_pandas().head(5)

print("\n" + "=" * 60)
print("SAMPLE ROWS")
print("=" * 60)

display(sample)

del sample
gc.collect()

============================================================
DATASET OVERVIEW
============================================================
Total rows       : 146,823,408
Total columns    : 30
Row groups       : 149

COLUMNS:
 1. year
 2. product_code
 3. exporter
 4. partner
 5. fobvalue
 6. qty
 7. product_description
 8. gdp
 9. gdp_growth
10. population
11. trade_percent_gdp
12. inflation
13. dist
14. contig
15. comlang_off
16. colony
17. continent_j
18. landlocked_j
19. global_imports
20. world_imports
21. global_demand_index
22. hhi
23. algeria_exports
24. market_share
25. penetration_ratio
26. trade_balance
27. product_diversity
28. opportunity_score
29. opportunity_level
30. export_growth

============================================================
SAMPLE ROWS
============================================================

,year,product_code,exporter,partner,fobvalue,qty,product_description,gdp,gdp_growth,population,...,global_demand_index,hhi,algeria_exports,market_share,penetration_ratio,trade_balance,product_diversity,opportunity_score,opportunity_level,export_growth
0,2010,610690,AFG,ALB,0.192,0.003,"Blouses, shirts and shirt-blouses: women's or ...",1.208655e+10,2.973155,2913021.0,...,0.000372,0.076895,0.000000,4.290042e-07,0.000376,0.192,7,0.400216,Medium,0.0
1,2010,621590,AFG,ALB,0.845,0.005,"Ties, bow ties and cravats: of textile materia...",1.208655e+10,2.973155,2913021.0,...,0.000044,0.175703,0.000000,1.599126e-05,0.002474,0.845,7,0.399799,Medium,0.0
2,2010,630900,AFG,ALB,0.317,0.017,"Clothing: worn, and other worn articles",1.208655e+10,2.973155,2913021.0,...,0.002385,0.080274,20.184000,3.589011e-05,0.000029,0.317,7,0.400863,Medium,0.0
3,2010,851999,AFG,ALB,0.150,0.001,Sound reproducing apparatus: other than casset...,1.208655e+10,2.973155,2913021.0,...,0.005072,0.308246,474.150024,6.395827e-06,0.000473,0.150,7,0.401610,Medium,0.0
4,2010,852810,AFG,ALB,0.188,0.014,"Television receivers: colour, whether or not c...",1.208655e+10,2.973155,2913021.0,...,0.084941,0.127898,130.994995,5.290362e-06,0.000006,0.188,7,0.425641,High,0.0

0

# Extract Years Safely

In [3]:
meta = pq.read_table(
    MASTER,
    columns=["year"]
).to_pandas()

YEARS = sorted(meta["year"].unique().tolist())

del meta
gc.collect()

print("Years found:")
print(YEARS)
print(f"\nTotal years: {len(YEARS)}")

Years found:
[2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2020, 2021, 2022, 2023, 2024]

Total years: 14

# Missing Values Analysis

In [4]:
missing_summary = []

for year in YEARS:

    print(f"Analyzing {year}...")

    yr = pq.read_table(
        MASTER,
        filters=[("year", "=", year)]
    ).to_pandas()

    miss = (
        yr.isna()
        .mean()
        .mul(100)
        .round(2)
        .reset_index()
    )

    miss.columns = ["column", "missing_pct"]
    miss["year"] = year

    missing_summary.append(miss)

    del yr, miss
    gc.collect()

missing_df = pd.concat(missing_summary, ignore_index=True)

print("\nTop missing columns:")
display(
    missing_df
    .sort_values("missing_pct", ascending=False)
    .head(30)
)

Analyzing 2010...
Analyzing 2011...
Analyzing 2012...
Analyzing 2013...
Analyzing 2014...
Analyzing 2015...
Analyzing 2016...
Analyzing 2017...
Analyzing 2018...
Analyzing 2020...
Analyzing 2021...
Analyzing 2022...
Analyzing 2023...
Analyzing 2024...

Top missing columns:

                column  missing_pct  year
400  trade_percent_gdp         9.34  2024
253             contig         7.61  2018
283             contig         7.61  2020
284        comlang_off         7.61  2020
282               dist         7.61  2020
252               dist         7.61  2018
285             colony         7.61  2020
254        comlang_off         7.61  2018
255             colony         7.61  2018
374        comlang_off         7.60  2023
373             contig         7.60  2023
372               dist         7.60  2023
375             colony         7.60  2023
343             contig         7.57  2022
344        comlang_off         7.57  2022
345             colony         7.57  2022
342               dist         7.57  2022
223             contig         7.51  2017
222               dist         7.51  2017
225             colony         7.51  2017
224        comlang_off         7.51  2017
315             colony         7.45  2021
314        comlang_off         7.45  2021
313             contig         7.45  2021
312               dist         7.45  2021
403             contig         7.44  2024
402               dist         7.44  2024
405             colony         7.44  2024
404        comlang_off         7.44  2024
195             colony         7.43  2016

# Main Cleaning Pipeline

In [5]:
writer = None

for year in YEARS:

    print(f"\nCleaning year {year}...", end=" ")

    yr = pq.read_table(
        MASTER,
        filters=[("year", "=", year)]
    ).to_pandas()

    # ────────────────────────────────────────
    # MEMORY OPTIMIZATION
    # ────────────────────────────────────────

    for col in yr.select_dtypes("float64").columns:
        yr[col] = yr[col].astype("float32")

    # ────────────────────────────────────────
    # REMOVE DUPLICATES
    # ────────────────────────────────────────

    yr = yr.drop_duplicates()

    # ────────────────────────────────────────
    # HANDLE INFINITE VALUES
    # ────────────────────────────────────────

    yr = yr.replace([np.inf, -np.inf], np.nan)

    # ────────────────────────────────────────
    # ECONOMIC INDICATORS
    # ────────────────────────────────────────

    econ_cols = [
        "gdp",
        "gdp_growth",
        "population",
        "trade_percent_gdp",
        "inflation"
    ]

    for col in econ_cols:

        if col in yr.columns:

            # country median
            med = (
                yr.groupby("partner")[col]
                .transform("median")
            )

            yr[col] = yr[col].fillna(med)

            # global fallback
            yr[col] = yr[col].fillna(
                yr[col].median()
            )

    # ────────────────────────────────────────
    # TRADE VARIABLES
    # ────────────────────────────────────────

    trade_cols = [
        "qty",
        "netWgt",
        "global_imports",
        "world_imports"
    ]

    for col in trade_cols:

        if col in yr.columns:

            med = (
                yr.groupby("product_code")[col]
                .transform("median")
            )

            yr[col] = yr[col].fillna(med)

            yr[col] = yr[col].fillna(
                yr[col].median()
            )

    # ────────────────────────────────────────
    # ENGINEERED FEATURES
    # ────────────────────────────────────────

    zero_cols = [
        "market_share",
        "penetration_ratio",
        "export_growth",
        "trade_balance",
        "global_demand_index"
    ]

    for col in zero_cols:

        if col in yr.columns:

            yr[col] = yr[col].fillna(0)

    # ────────────────────────────────────────
    # CATEGORICAL VARIABLES
    # ────────────────────────────────────────

    cat_cols = yr.select_dtypes(include="object").columns

    for col in cat_cols:

        yr[col] = yr[col].fillna("Unknown")

    # ────────────────────────────────────────
    # FINAL NUMERIC SAFETY
    # ────────────────────────────────────────

    num_cols = yr.select_dtypes(include=np.number).columns

    for col in num_cols:

        yr[col] = yr[col].fillna(
            yr[col].median()
        )

    # ────────────────────────────────────────
    # WRITE YEAR
    # ────────────────────────────────────────

    table = pa.Table.from_pandas(
        yr,
        preserve_index=False
    )

    if writer is None:

        writer = pq.ParquetWriter(
            OUT,
            table.schema,
            compression="snappy"
        )

    try:
        writer.write_table(table)

    except Exception:
        writer.write_table(table.cast(writer.schema))

    print(f"{len(yr):,} rows")

    del yr, table
    gc.collect()

writer.close()

print("\nDONE")
print(f"Saved file → {OUT}")
print(f"Size       → {os.path.getsize(OUT)/1e6:.1f} MB")

Cleaning year 2010... 9,470,765 rows

Cleaning year 2011... 9,640,712 rows

Cleaning year 2012... 9,937,050 rows

Cleaning year 2013... 10,098,942 rows

Cleaning year 2014... 10,145,672 rows

Cleaning year 2015... 10,499,686 rows

Cleaning year 2016... 10,569,571 rows

Cleaning year 2017... 10,821,738 rows

Cleaning year 2018... 10,924,964 rows

Cleaning year 2020... 10,638,241 rows

Cleaning year 2021... 11,146,476 rows

Cleaning year 2022... 11,154,874 rows

Cleaning year 2023... 11,194,668 rows

Cleaning year 2024... 10,580,049 rows

DONE
Saved file → /kaggle/working/algeria_trade_master_cleaned.parquet
Size       → 5704.3 MB

# Verification

In [6]:
pf = pq.ParquetFile(OUT)

print("=" * 60)
print("CLEANED DATASET")
print("=" * 60)

print(f"Rows       : {pf.metadata.num_rows:,}")
print(f"Columns    : {pf.metadata.num_columns}")
print(f"Row groups : {pf.num_row_groups}")

sample = pf.read_row_group(0).to_pandas().head(5)

print("\nSample:")
display(sample)

del sample
gc.collect()

============================================================
CLEANED DATASET
============================================================
Rows       : 146,823,408
Columns    : 30
Row groups : 149

Sample:

,year,product_code,exporter,partner,fobvalue,qty,product_description,gdp,gdp_growth,population,...,global_demand_index,hhi,algeria_exports,market_share,penetration_ratio,trade_balance,product_diversity,opportunity_score,opportunity_level,export_growth
0,2010,610690,AFG,ALB,0.192,0.003,"Blouses, shirts and shirt-blouses: women's or ...",1.208655e+10,2.973155,2913021.0,...,0.000372,0.076895,0.000000,4.290042e-07,0.000376,0.192,7,0.400216,Medium,0.0
1,2010,621590,AFG,ALB,0.845,0.005,"Ties, bow ties and cravats: of textile materia...",1.208655e+10,2.973155,2913021.0,...,0.000044,0.175703,0.000000,1.599126e-05,0.002474,0.845,7,0.399799,Medium,0.0
2,2010,630900,AFG,ALB,0.317,0.017,"Clothing: worn, and other worn articles",1.208655e+10,2.973155,2913021.0,...,0.002385,0.080274,20.184000,3.589011e-05,0.000029,0.317,7,0.400863,Medium,0.0
3,2010,851999,AFG,ALB,0.150,0.001,Sound reproducing apparatus: other than casset...,1.208655e+10,2.973155,2913021.0,...,0.005072,0.308246,474.150024,6.395827e-06,0.000473,0.150,7,0.401610,Medium,0.0
4,2010,852810,AFG,ALB,0.188,0.014,"Television receivers: colour, whether or not c...",1.208655e+10,2.973155,2913021.0,...,0.084941,0.127898,130.994995,5.290362e-06,0.000006,0.188,7,0.425641,High,0.0

2

# Cleaning Statistics

In [7]:
# ─────────────────────────────────────────────
# Compare original vs cleaned dataset
# ─────────────────────────────────────────────

original_pf = pq.ParquetFile(MASTER)
clean_pf    = pq.ParquetFile(OUT)

original_rows = original_pf.metadata.num_rows
clean_rows    = clean_pf.metadata.num_rows

removed_rows = original_rows - clean_rows

print("=" * 60)
print("CLEANING SUMMARY")
print("=" * 60)

print(f"Original rows : {original_rows:,}")
print(f"Cleaned rows  : {clean_rows:,}")
print(f"Removed rows  : {removed_rows:,}")

print("\nPercentage removed:")
print(f"{(removed_rows / original_rows) * 100:.4f}%")

============================================================
CLEANING SUMMARY
============================================================
Original rows : 146,823,408
Cleaned rows  : 146,823,408
Removed rows  : 0

Percentage removed:
0.0000%

In [8]:
import pyarrow.parquet as pq
import pandas as pd
import gc

pf = pq.ParquetFile(OUT)

total_duplicates = 0
total_rows = 0

for i in range(pf.num_row_groups):

    print(f"Checking row group {i+1}/{pf.num_row_groups}...")

    chunk = pf.read_row_group(i).to_pandas()

    dup_count = chunk.duplicated().sum()

    total_duplicates += dup_count
    total_rows += len(chunk)

    print(f"  Rows       : {len(chunk):,}")
    print(f"  Duplicates : {dup_count:,}")

    del chunk
    gc.collect()

print("\n" + "="*60)
print("DUPLICATE SUMMARY")
print("="*60)

print(f"Total rows checked : {total_rows:,}")
print(f"Total duplicates   : {total_duplicates:,}")
print(f"Duplicate %        : {(total_duplicates/total_rows)*100:.6f}%")

Checking row group 1/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 2/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 3/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 4/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 5/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 6/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 7/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 8/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 9/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 10/149...
  Rows       : 33,581
  Duplicates : 0
Checking row group 11/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 12/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 13/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 14/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 15/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 16/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 17/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 18/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 19/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 20/149...
  Rows       : 203,528
  Duplicates : 0
Checking row group 21/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 22/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 23/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 24/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 25/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 26/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 27/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 28/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 29/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 30/149...
  Rows       : 499,866
  Duplicates : 0
Checking row group 31/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 32/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 33/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 34/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 35/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 36/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 37/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 38/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 39/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 40/149...
  Rows       : 661,758
  Duplicates : 0
Checking row group 41/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 42/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 43/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 44/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 45/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 46/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 47/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 48/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 49/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 50/149...
  Rows       : 708,488
  Duplicates : 0
Checking row group 51/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 52/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 53/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 54/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 55/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 56/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 57/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 58/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 59/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 60/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 61/149...
  Rows       : 13,926
  Duplicates : 0
Checking row group 62/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 63/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 64/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 65/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 66/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 67/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 68/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 69/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 70/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 71/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 72/149...
  Rows       : 83,811
  Duplicates : 0
Checking row group 73/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 74/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 75/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 76/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 77/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 78/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 79/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 80/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 81/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 82/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 83/149...
  Rows       : 335,978
  Duplicates : 0
Checking row group 84/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 85/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 86/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 87/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 88/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 89/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 90/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 91/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 92/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 93/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 94/149...
  Rows       : 439,204
  Duplicates : 0
Checking row group 95/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 96/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 97/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 98/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 99/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 100/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 101/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 102/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 103/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 104/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 105/149...
  Rows       : 152,481
  Duplicates : 0
Checking row group 106/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 107/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 108/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 109/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 110/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 111/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 112/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 113/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 114/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 115/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 116/149...
  Rows       : 660,716
  Duplicates : 0
Checking row group 117/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 118/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 119/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 120/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 121/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 122/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 123/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 124/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 125/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 126/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 127/149...
  Rows       : 669,114
  Duplicates : 0
Checking row group 128/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 129/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 130/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 131/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 132/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 133/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 134/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 135/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 136/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 137/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 138/149...
  Rows       : 708,908
  Duplicates : 0
Checking row group 139/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 140/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 141/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 142/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 143/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 144/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 145/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 146/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 147/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 148/149...
  Rows       : 1,048,576
  Duplicates : 0
Checking row group 149/149...
  Rows       : 94,289
  Duplicates : 0

============================================================
DUPLICATE SUMMARY
============================================================
Total rows checked : 146,823,408
Total duplicates   : 0
Duplicate %        : 0.000000%

In [9]:
import pyarrow.parquet as pq
import pandas as pd
import numpy as np
import gc

# ─────────────────────────────────────────────
# Open parquet files
# ─────────────────────────────────────────────

orig_pf  = pq.ParquetFile(MASTER)
clean_pf = pq.ParquetFile(OUT)

original_missing = 0
clean_missing    = 0

# ─────────────────────────────────────────────
# Process row group by row group
# ─────────────────────────────────────────────

for i in range(orig_pf.num_row_groups):

    print(f"Checking row group {i+1}/{orig_pf.num_row_groups}...")

    # original chunk
    orig_chunk = orig_pf.read_row_group(i).to_pandas()

    # cleaned chunk
    clean_chunk = clean_pf.read_row_group(i).to_pandas()

    # count missing cells
    orig_na  = orig_chunk.isna().sum().sum()
    clean_na = clean_chunk.isna().sum().sum()

    original_missing += orig_na
    clean_missing    += clean_na

    print(f"  Original missing : {orig_na:,}")
    print(f"  Cleaned missing  : {clean_na:,}")

    del orig_chunk, clean_chunk
    gc.collect()

# ─────────────────────────────────────────────
# Final summary
# ─────────────────────────────────────────────

filled_cells = original_missing - clean_missing

print("\n" + "="*60)
print("MISSING VALUE CLEANING SUMMARY")
print("="*60)

print(f"Original missing cells : {original_missing:,}")
print(f"Remaining missing cells: {clean_missing:,}")
print(f"Filled missing cells   : {filled_cells:,}")

if original_missing > 0:

    pct = (filled_cells / original_missing) * 100

    print(f"\nPercentage fixed       : {pct:.4f}%")

Checking row group 1/149...
  Original missing : 320,408
  Cleaned missing  : 41,431
Checking row group 2/149...
  Original missing : 300,872
  Cleaned missing  : 35,867
Checking row group 3/149...
  Original missing : 296,095
  Cleaned missing  : 35,982
Checking row group 4/149...
  Original missing : 338,040
  Cleaned missing  : 44,713
Checking row group 5/149...
  Original missing : 849,240
  Cleaned missing  : 33,003
Checking row group 6/149...
  Original missing : 490,077
  Cleaned missing  : 33,044
Checking row group 7/149...
  Original missing : 734,239
  Cleaned missing  : 39,683
Checking row group 8/149...
  Original missing : 242,379
  Cleaned missing  : 31,028
Checking row group 9/149...
  Original missing : 282,147
  Cleaned missing  : 36,987
Checking row group 10/149...
  Original missing : 14,161
  Cleaned missing  : 2,017
Checking row group 11/149...
  Original missing : 325,079
  Cleaned missing  : 43,019
Checking row group 12/149...
  Original missing : 298,179
  Cleaned missing  : 37,855
Checking row group 13/149...
  Original missing : 319,219
  Cleaned missing  : 39,894
Checking row group 14/149...
  Original missing : 344,077
  Cleaned missing  : 46,274
Checking row group 15/149...
  Original missing : 553,750
  Cleaned missing  : 31,726
Checking row group 16/149...
  Original missing : 821,123
  Cleaned missing  : 37,949
Checking row group 17/149...
  Original missing : 762,109
  Cleaned missing  : 41,777
Checking row group 18/149...
  Original missing : 264,801
  Cleaned missing  : 34,338
Checking row group 19/149...
  Original missing : 295,788
  Cleaned missing  : 37,905
Checking row group 20/149...
  Original missing : 52,578
  Cleaned missing  : 7,831
Checking row group 21/149...
  Original missing : 323,258
  Cleaned missing  : 42,973
Checking row group 22/149...
  Original missing : 301,784
  Cleaned missing  : 38,915
Checking row group 23/149...
  Original missing : 317,086
  Cleaned missing  : 38,164
Checking row group 24/149...
  Original missing : 326,482
  Cleaned missing  : 43,259
Checking row group 25/149...
  Original missing : 270,816
  Cleaned missing  : 34,919
Checking row group 26/149...
  Original missing : 1,119,513
  Cleaned missing  : 35,666
Checking row group 27/149...
  Original missing : 753,538
  Cleaned missing  : 36,682
Checking row group 28/149...
  Original missing : 315,431
  Cleaned missing  : 42,958
Checking row group 29/149...
  Original missing : 285,273
  Cleaned missing  : 38,091
Checking row group 30/149...
  Original missing : 137,802
  Cleaned missing  : 16,695
Checking row group 31/149...
  Original missing : 329,703
  Cleaned missing  : 44,167
Checking row group 32/149...
  Original missing : 311,424
  Cleaned missing  : 40,202
Checking row group 33/149...
  Original missing : 316,739
  Cleaned missing  : 36,370
Checking row group 34/149...
  Original missing : 310,304
  Cleaned missing  : 42,888
Checking row group 35/149...
  Original missing : 334,679
  Cleaned missing  : 43,546
Checking row group 36/149...
  Original missing : 1,109,197
  Cleaned missing  : 35,081
Checking row group 37/149...
  Original missing : 779,372
  Cleaned missing  : 36,324
Checking row group 38/149...
  Original missing : 309,245
  Cleaned missing  : 41,321
Checking row group 39/149...
  Original missing : 265,040
  Cleaned missing  : 35,963
Checking row group 40/149...
  Original missing : 221,337
  Cleaned missing  : 27,218
Checking row group 41/149...
  Original missing : 325,375
  Cleaned missing  : 43,701
Checking row group 42/149...
  Original missing : 309,387
  Cleaned missing  : 40,685
Checking row group 43/149...
  Original missing : 283,757
  Cleaned missing  : 33,615
Checking row group 44/149...
  Original missing : 303,606
  Cleaned missing  : 42,474
Checking row group 45/149...
  Original missing : 309,435
  Cleaned missing  : 39,751
Checking row group 46/149...
  Original missing : 1,103,024
  Cleaned missing  : 35,017
Checking row group 47/149...
  Original missing : 802,894
  Cleaned missing  : 37,453
Checking row group 48/149...
  Original missing : 313,620
  Cleaned missing  : 41,895
Checking row group 49/149...
  Original missing : 276,974
  Cleaned missing  : 37,961
Checking row group 50/149...
  Original missing : 218,938
  Cleaned missing  : 26,892
Checking row group 51/149...
  Original missing : 335,340
  Cleaned missing  : 45,612
Checking row group 52/149...
  Original missing : 309,960
  Cleaned missing  : 39,337
Checking row group 53/149...
  Original missing : 287,861
  Cleaned missing  : 36,439
Checking row group 54/149...
  Original missing : 359,420
  Cleaned missing  : 48,929
Checking row group 55/149...
  Original missing : 318,867
  Cleaned missing  : 43,291
Checking row group 56/149...
  Original missing : 1,113,616
  Cleaned missing  : 38,951
Checking row group 57/149...
  Original missing : 861,511
  Cleaned missing  : 38,739
Checking row group 58/149...
  Original missing : 311,409
  Cleaned missing  : 40,724
Checking row group 59/149...
  Original missing : 279,715
  Cleaned missing  : 38,173
Checking row group 60/149...
  Original missing : 340,475
  Cleaned missing  : 45,485
Checking row group 61/149...
  Original missing : 10,852
  Cleaned missing  : 1,700
Checking row group 62/149...
  Original missing : 341,731
  Cleaned missing  : 46,447
Checking row group 63/149...
  Original missing : 301,471
  Cleaned missing  : 38,491
Checking row group 64/149...
  Original missing : 306,668
  Cleaned missing  : 38,551
Checking row group 65/149...
  Original missing : 371,683
  Cleaned missing  : 50,803
Checking row group 66/149...
  Original missing : 304,445
  Cleaned missing  : 41,129
Checking row group 67/149...
  Original missing : 1,101,980
  Cleaned missing  : 38,901
Checking row group 68/149...
  Original missing : 792,640
  Cleaned missing  : 36,090
Checking row group 69/149...
  Original missing : 383,660
  Cleaned missing  : 41,780
Checking row group 70/149...
  Original missing : 295,205
  Cleaned missing  : 39,400
Checking row group 71/149...
  Original missing : 365,443
  Cleaned missing  : 48,464
Checking row group 72/149...
  Original missing : 13,635
  Cleaned missing  : 2,026
Checking row group 73/149...
  Original missing : 346,067
  Cleaned missing  : 47,006
Checking row group 74/149...
  Original missing : 319,505
  Cleaned missing  : 40,864
Checking row group 75/149...
  Original missing : 306,797
  Cleaned missing  : 38,571
Checking row group 76/149...
  Original missing : 365,913
  Cleaned missing  : 50,649
Checking row group 77/149...
  Original missing : 329,239
  Cleaned missing  : 44,818
Checking row group 78/149...
  Original missing : 1,040,912
  Cleaned missing  : 34,593
Checking row group 79/149...
  Original missing : 763,022
  Cleaned missing  : 41,952
Checking row group 80/149...
  Original missing : 563,711
  Cleaned missing  : 48,823
Checking row group 81/149...
  Original missing : 275,527
  Cleaned missing  : 36,934
Checking row group 82/149...
  Original missing : 281,745
  Cleaned missing  : 39,293
Checking row group 83/149...
  Original missing : 150,069
  Cleaned missing  : 19,022
Checking row group 84/149...
  Original missing : 350,979
  Cleaned missing  : 47,805
Checking row group 85/149...
  Original missing : 327,869
  Cleaned missing  : 41,934
Checking row group 86/149...
  Original missing : 319,211
  Cleaned missing  : 40,213
Checking row group 87/149...
  Original missing : 357,540
  Cleaned missing  : 49,433
Checking row group 88/149...
  Original missing : 339,369
  Cleaned missing  : 46,401
Checking row group 89/149...
  Original missing : 994,281
  Cleaned missing  : 29,561
Checking row group 90/149...
  Original missing : 837,018
  Cleaned missing  : 49,539
Checking row group 91/149...
  Original missing : 551,589
  Cleaned missing  : 47,177
Checking row group 92/149...
  Original missing : 302,595
  Cleaned missing  : 39,891
Checking row group 93/149...
  Original missing : 307,160
  Cleaned missing  : 43,789
Checking row group 94/149...
  Original missing : 162,871
  Cleaned missing  : 20,633
Checking row group 95/149...
  Original missing : 432,518
  Cleaned missing  : 48,137
Checking row group 96/149...
  Original missing : 470,497
  Cleaned missing  : 42,801
Checking row group 97/149...
  Original missing : 390,126
  Cleaned missing  : 39,104
Checking row group 98/149...
  Original missing : 458,847
  Cleaned missing  : 53,580
Checking row group 99/149...
  Original missing : 404,976
  Cleaned missing  : 43,417
Checking row group 100/149...
  Original missing : 1,164,031
  Cleaned missing  : 40,508
Checking row group 101/149...
  Original missing : 838,946
  Cleaned missing  : 40,729
Checking row group 102/149...
  Original missing : 615,709
  Cleaned missing  : 45,530
Checking row group 103/149...
  Original missing : 405,945
  Cleaned missing  : 39,146
Checking row group 104/149...
  Original missing : 513,762
  Cleaned missing  : 49,302
Checking row group 105/149...
  Original missing : 78,465
  Cleaned missing  : 8,045
Checking row group 106/149...
  Original missing : 400,698
  Cleaned missing  : 41,799
Checking row group 107/149...
  Original missing : 465,198
  Cleaned missing  : 41,555
Checking row group 108/149...
  Original missing : 417,367
  Cleaned missing  : 46,487
Checking row group 109/149...
  Original missing : 434,404
  Cleaned missing  : 47,757
Checking row group 110/149...
  Original missing : 432,571
  Cleaned missing  : 46,537
Checking row group 111/149...
  Original missing : 1,012,478
  Cleaned missing  : 29,324
Checking row group 112/149...
  Original missing : 482,465
  Cleaned missing  : 44,437
Checking row group 113/149...
  Original missing : 1,075,431
  Cleaned missing  : 42,888
Checking row group 114/149...
  Original missing : 403,768
  Cleaned missing  : 43,802
Checking row group 115/149...
  Original missing : 435,427
  Cleaned missing  : 42,396
Checking row group 116/149...
  Original missing : 340,895
  Cleaned missing  : 29,793
Checking row group 117/149...
  Original missing : 413,405
  Cleaned missing  : 43,000
Checking row group 118/149...
  Original missing : 471,578
  Cleaned missing  : 41,934
Checking row group 119/149...
  Original missing : 423,685
  Cleaned missing  : 47,688
Checking row group 120/149...
  Original missing : 444,776
  Cleaned missing  : 48,779
Checking row group 121/149...
  Original missing : 430,681
  Cleaned missing  : 46,466
Checking row group 122/149...
  Original missing : 1,002,780
  Cleaned missing  : 29,887
Checking row group 123/149...
  Original missing : 486,461
  Cleaned missing  : 45,206
Checking row group 124/149...
  Original missing : 1,112,203
  Cleaned missing  : 43,620
Checking row group 125/149...
  Original missing : 404,566
  Cleaned missing  : 44,093
Checking row group 126/149...
  Original missing : 442,136
  Cleaned missing  : 43,134
Checking row group 127/149...
  Original missing : 347,687
  Cleaned missing  : 30,218
Checking row group 128/149...
  Original missing : 432,896
  Cleaned missing  : 43,823
Checking row group 129/149...
  Original missing : 495,354
  Cleaned missing  : 43,168
Checking row group 130/149...
  Original missing : 458,575
  Cleaned missing  : 50,424
Checking row group 131/149...
  Original missing : 433,720
  Cleaned missing  : 44,898
Checking row group 132/149...
  Original missing : 450,689
  Cleaned missing  : 47,977
Checking row group 133/149...
  Original missing : 1,028,560
  Cleaned missing  : 34,134
Checking row group 134/149...
  Original missing : 471,693
  Cleaned missing  : 41,214
Checking row group 135/149...
  Original missing : 1,142,665
  Cleaned missing  : 44,686
Checking row group 136/149...
  Original missing : 433,712
  Cleaned missing  : 46,656
Checking row group 137/149...
  Original missing : 469,026
  Cleaned missing  : 43,806
Checking row group 138/149...
  Original missing : 373,488
  Cleaned missing  : 30,730
Checking row group 139/149...
  Original missing : 471,887
  Cleaned missing  : 43,427
Checking row group 140/149...
  Original missing : 538,931
  Cleaned missing  : 44,326
Checking row group 141/149...
  Original missing : 470,809
  Cleaned missing  : 42,174
Checking row group 142/149...
  Original missing : 470,160
  Cleaned missing  : 47,488
Checking row group 143/149...
  Original missing : 445,966
  Cleaned missing  : 40,345
Checking row group 144/149...
  Original missing : 1,104,425
  Cleaned missing  : 41,256
Checking row group 145/149...
  Original missing : 882,433
  Cleaned missing  : 34,763
Checking row group 146/149...
  Original missing : 735,067
  Cleaned missing  : 44,055
Checking row group 147/149...
  Original missing : 438,585
  Cleaned missing  : 36,963
Checking row group 148/149...
  Original missing : 592,058
  Cleaned missing  : 49,228
Checking row group 149/149...
  Original missing : 41,677
  Cleaned missing  : 2,181

============================================================
MISSING VALUE CLEANING SUMMARY
============================================================
Original missing cells : 69,326,828
Remaining missing cells: 5,830,353
Filled missing cells   : 63,496,475

Percentage fixed       : 91.5900%

In [10]:
import pyarrow.parquet as pq
import pandas as pd
import gc

pf = pq.ParquetFile(OUT)

missing_by_col = {}

for i in range(pf.num_row_groups):

    print(f"Analyzing row group {i+1}/{pf.num_row_groups}...")

    chunk = pf.read_row_group(i).to_pandas()

    miss = chunk.isna().sum()

    for col, val in miss.items():

        missing_by_col[col] = (
            missing_by_col.get(col, 0) + val
        )

    del chunk
    gc.collect()

missing_df = pd.DataFrame({
    "column": missing_by_col.keys(),
    "missing_cells": missing_by_col.values()
})

missing_df["missing_pct"] = (
    missing_df["missing_cells"]
    /
    pf.metadata.num_rows
) * 100

missing_df = missing_df.sort_values(
    "missing_cells",
    ascending=False
)

print("\nColumns with remaining missing values:\n")

display(missing_df)

Analyzing row group 1/149...
Analyzing row group 2/149...
Analyzing row group 3/149...
Analyzing row group 4/149...
Analyzing row group 5/149...
Analyzing row group 6/149...
Analyzing row group 7/149...
Analyzing row group 8/149...
Analyzing row group 9/149...
Analyzing row group 10/149...
Analyzing row group 11/149...
Analyzing row group 12/149...
Analyzing row group 13/149...
Analyzing row group 14/149...
Analyzing row group 15/149...
Analyzing row group 16/149...
Analyzing row group 17/149...
Analyzing row group 18/149...
Analyzing row group 19/149...
Analyzing row group 20/149...
Analyzing row group 21/149...
Analyzing row group 22/149...
Analyzing row group 23/149...
Analyzing row group 24/149...
Analyzing row group 25/149...
Analyzing row group 26/149...
Analyzing row group 27/149...
Analyzing row group 28/149...
Analyzing row group 29/149...
Analyzing row group 30/149...
Analyzing row group 31/149...
Analyzing row group 32/149...
Analyzing row group 33/149...
Analyzing row group 34/149...
Analyzing row group 35/149...
Analyzing row group 36/149...
Analyzing row group 37/149...
Analyzing row group 38/149...
Analyzing row group 39/149...
Analyzing row group 40/149...
Analyzing row group 41/149...
Analyzing row group 42/149...
Analyzing row group 43/149...
Analyzing row group 44/149...
Analyzing row group 45/149...
Analyzing row group 46/149...
Analyzing row group 47/149...
Analyzing row group 48/149...
Analyzing row group 49/149...
Analyzing row group 50/149...
Analyzing row group 51/149...
Analyzing row group 52/149...
Analyzing row group 53/149...
Analyzing row group 54/149...
Analyzing row group 55/149...
Analyzing row group 56/149...
Analyzing row group 57/149...
Analyzing row group 58/149...
Analyzing row group 59/149...
Analyzing row group 60/149...
Analyzing row group 61/149...
Analyzing row group 62/149...
Analyzing row group 63/149...
Analyzing row group 64/149...
Analyzing row group 65/149...
Analyzing row group 66/149...
Analyzing row group 67/149...
Analyzing row group 68/149...
Analyzing row group 69/149...
Analyzing row group 70/149...
Analyzing row group 71/149...
Analyzing row group 72/149...
Analyzing row group 73/149...
Analyzing row group 74/149...
Analyzing row group 75/149...
Analyzing row group 76/149...
Analyzing row group 77/149...
Analyzing row group 78/149...
Analyzing row group 79/149...
Analyzing row group 80/149...
Analyzing row group 81/149...
Analyzing row group 82/149...
Analyzing row group 83/149...
Analyzing row group 84/149...
Analyzing row group 85/149...
Analyzing row group 86/149...
Analyzing row group 87/149...
Analyzing row group 88/149...
Analyzing row group 89/149...
Analyzing row group 90/149...
Analyzing row group 91/149...
Analyzing row group 92/149...
Analyzing row group 93/149...
Analyzing row group 94/149...
Analyzing row group 95/149...
Analyzing row group 96/149...
Analyzing row group 97/149...
Analyzing row group 98/149...
Analyzing row group 99/149...
Analyzing row group 100/149...
Analyzing row group 101/149...
Analyzing row group 102/149...
Analyzing row group 103/149...
Analyzing row group 104/149...
Analyzing row group 105/149...
Analyzing row group 106/149...
Analyzing row group 107/149...
Analyzing row group 108/149...
Analyzing row group 109/149...
Analyzing row group 110/149...
Analyzing row group 111/149...
Analyzing row group 112/149...
Analyzing row group 113/149...
Analyzing row group 114/149...
Analyzing row group 115/149...
Analyzing row group 116/149...
Analyzing row group 117/149...
Analyzing row group 118/149...
Analyzing row group 119/149...
Analyzing row group 120/149...
Analyzing row group 121/149...
Analyzing row group 122/149...
Analyzing row group 123/149...
Analyzing row group 124/149...
Analyzing row group 125/149...
Analyzing row group 126/149...
Analyzing row group 127/149...
Analyzing row group 128/149...
Analyzing row group 129/149...
Analyzing row group 130/149...
Analyzing row group 131/149...
Analyzing row group 132/149...
Analyzing row group 133/149...
Analyzing row group 134/149...
Analyzing row group 135/149...
Analyzing row group 136/149...
Analyzing row group 137/149...
Analyzing row group 138/149...
Analyzing row group 139/149...
Analyzing row group 140/149...
Analyzing row group 141/149...
Analyzing row group 142/149...
Analyzing row group 143/149...
Analyzing row group 144/149...
Analyzing row group 145/149...
Analyzing row group 146/149...
Analyzing row group 147/149...
Analyzing row group 148/149...
Analyzing row group 149/149...

Columns with remaining missing values:

                 column  missing_cells  missing_pct
16          continent_j        5830353     3.970997
0                  year              0     0.000000
2              exporter              0     0.000000
3               partner              0     0.000000
4              fobvalue              0     0.000000
1          product_code              0     0.000000
6   product_description              0     0.000000
7                   gdp              0     0.000000
8            gdp_growth              0     0.000000
9            population              0     0.000000
10    trade_percent_gdp              0     0.000000
11            inflation              0     0.000000
12                 dist              0     0.000000
5                   qty              0     0.000000
13               contig              0     0.000000
14          comlang_off              0     0.000000
15               colony              0     0.000000
17         landlocked_j              0     0.000000
18       global_imports              0     0.000000
19        world_imports              0     0.000000
20  global_demand_index              0     0.000000
21                  hhi              0     0.000000
22      algeria_exports              0     0.000000
23         market_share              0     0.000000
24    penetration_ratio              0     0.000000
25        trade_balance              0     0.000000
26    product_diversity              0     0.000000
27    opportunity_score              0     0.000000
28    opportunity_level              0     0.000000
29        export_growth              0     0.000000

In [11]:
# ============================================================
# FINAL ML-READY CLEANING CELL (FIXED VERSION)
# -> handles remaining missing values
# -> fixes categorical errors
# -> guarantees 0 missing values
# -> creates FINAL ML-ready dataset
# ============================================================

import pyarrow.parquet as pq
import pyarrow as pa
import pandas as pd
import numpy as np
import os
import gc

# ------------------------------------------------------------
# INPUT / OUTPUT
# ------------------------------------------------------------

INPUT_FILE = OUT

FINAL_DATASET = "/kaggle/working/algeria_trade_master_ml_ready.parquet"

pf = pq.ParquetFile(INPUT_FILE)

writer = None

# ============================================================
# STEP 1 — BUILD continent lookup
# ============================================================

print("=" * 60)
print("STEP 1 — Building continent lookup")
print("=" * 60)

continent_lookup = {}

for i in range(pf.num_row_groups):

    chunk = pf.read_row_group(
        i,
        columns=["partner", "continent_j"]
    ).to_pandas()

    # convert safely
    chunk["continent_j"] = chunk["continent_j"].astype("object")

    valid = chunk.dropna(subset=["continent_j"])

    grouped = (
        valid.groupby("partner")["continent_j"]
        .agg(
            lambda x:
            x.mode().iloc[0]
            if not x.mode().empty
            else "Unknown"
        )
    )

    for k, v in grouped.items():

        if k not in continent_lookup:
            continent_lookup[k] = v

    del chunk, valid, grouped
    gc.collect()

print(f"Lookup size: {len(continent_lookup):,}")

# ============================================================
# STEP 2 — FINAL CLEANING
# ============================================================

print("\n" + "=" * 60)
print("STEP 2 — Final cleaning")
print("=" * 60)

for i in range(pf.num_row_groups):

    print(f"Processing row group {i+1}/{pf.num_row_groups}...")

    chunk = pf.read_row_group(i).to_pandas()

    # --------------------------------------------------------
    # FIX continent_j
    # --------------------------------------------------------

    chunk["continent_j"] = (
        chunk["continent_j"]
        .astype("object")
    )

    chunk["continent_j"] = chunk["continent_j"].fillna(
        chunk["partner"].map(continent_lookup)
    )

    chunk["continent_j"] = chunk["continent_j"].fillna("Unknown")

    # --------------------------------------------------------
    # HANDLE categorical/object columns
    # --------------------------------------------------------

    cat_cols = chunk.select_dtypes(
        include=["object", "category"]
    ).columns

    for col in cat_cols:

        chunk[col] = chunk[col].astype("object")

        chunk[col] = chunk[col].fillna("Unknown")

    # --------------------------------------------------------
    # HANDLE numeric columns
    # --------------------------------------------------------

    num_cols = chunk.select_dtypes(
        include=np.number
    ).columns

    for col in num_cols:

        chunk[col] = chunk[col].replace(
            [np.inf, -np.inf],
            np.nan
        )

        chunk[col] = chunk[col].fillna(
            chunk[col].median()
        )

    # --------------------------------------------------------
    # MEMORY OPTIMIZATION
    # --------------------------------------------------------

    for col in chunk.select_dtypes("float64").columns:

        chunk[col] = chunk[col].astype("float32")

    # --------------------------------------------------------
    # WRITE parquet incrementally
    # --------------------------------------------------------

    table = pa.Table.from_pandas(
        chunk,
        preserve_index=False
    )

    if writer is None:

        writer = pq.ParquetWriter(
            FINAL_DATASET,
            table.schema,
            compression="snappy"
        )

    try:

        writer.write_table(table)

    except Exception:

        writer.write_table(
            table.cast(writer.schema)
        )

    del chunk, table
    gc.collect()

writer.close()

# ============================================================
# STEP 3 — VERIFY FINAL DATASET
# ============================================================

print("\n" + "=" * 60)
print("STEP 3 — Verification")
print("=" * 60)

final_pf = pq.ParquetFile(FINAL_DATASET)

missing_total = 0

for i in range(final_pf.num_row_groups):

    chunk = final_pf.read_row_group(i).to_pandas()

    missing_total += chunk.isna().sum().sum()

    del chunk
    gc.collect()

print(f"\nFinal rows       : {final_pf.metadata.num_rows:,}")
print(f"Final columns    : {final_pf.metadata.num_columns}")
print(f"Final row groups : {final_pf.num_row_groups}")

print(f"\nRemaining missing values : {missing_total:,}")

if missing_total == 0:

    print("\nSUCCESS — Dataset is fully ML-ready.")

else:

    print("\nSome missing values still remain.")

print(f"\nSaved file:")
print(FINAL_DATASET)

print(f"\nFile size:")
print(f"{os.path.getsize(FINAL_DATASET)/1e6:.1f} MB")

============================================================
STEP 1 — Building continent lookup
============================================================
Lookup size: 212

============================================================
STEP 2 — Final cleaning
============================================================
Processing row group 1/149...
Processing row group 2/149...
Processing row group 3/149...
Processing row group 4/149...
Processing row group 5/149...
Processing row group 6/149...
Processing row group 7/149...
Processing row group 8/149...
Processing row group 9/149...
Processing row group 10/149...
Processing row group 11/149...
Processing row group 12/149...
Processing row group 13/149...
Processing row group 14/149...
Processing row group 15/149...
Processing row group 16/149...
Processing row group 17/149...
Processing row group 18/149...
Processing row group 19/149...
Processing row group 20/149...
Processing row group 21/149...
Processing row group 22/149...
Processing row group 23/149...
Processing row group 24/149...
Processing row group 25/149...
Processing row group 26/149...
Processing row group 27/149...
Processing row group 28/149...
Processing row group 29/149...
Processing row group 30/149...
Processing row group 31/149...
Processing row group 32/149...
Processing row group 33/149...
Processing row group 34/149...
Processing row group 35/149...
Processing row group 36/149...
Processing row group 37/149...
Processing row group 38/149...
Processing row group 39/149...
Processing row group 40/149...
Processing row group 41/149...
Processing row group 42/149...
Processing row group 43/149...
Processing row group 44/149...
Processing row group 45/149...
Processing row group 46/149...
Processing row group 47/149...
Processing row group 48/149...
Processing row group 49/149...
Processing row group 50/149...
Processing row group 51/149...
Processing row group 52/149...
Processing row group 53/149...
Processing row group 54/149...
Processing row group 55/149...
Processing row group 56/149...
Processing row group 57/149...
Processing row group 58/149...
Processing row group 59/149...
Processing row group 60/149...
Processing row group 61/149...
Processing row group 62/149...
Processing row group 63/149...
Processing row group 64/149...
Processing row group 65/149...
Processing row group 66/149...
Processing row group 67/149...
Processing row group 68/149...
Processing row group 69/149...
Processing row group 70/149...
Processing row group 71/149...
Processing row group 72/149...
Processing row group 73/149...
Processing row group 74/149...
Processing row group 75/149...
Processing row group 76/149...
Processing row group 77/149...
Processing row group 78/149...
Processing row group 79/149...
Processing row group 80/149...
Processing row group 81/149...
Processing row group 82/149...
Processing row group 83/149...
Processing row group 84/149...
Processing row group 85/149...
Processing row group 86/149...
Processing row group 87/149...
Processing row group 88/149...
Processing row group 89/149...
Processing row group 90/149...
Processing row group 91/149...
Processing row group 92/149...
Processing row group 93/149...
Processing row group 94/149...
Processing row group 95/149...
Processing row group 96/149...
Processing row group 97/149...
Processing row group 98/149...
Processing row group 99/149...
Processing row group 100/149...
Processing row group 101/149...
Processing row group 102/149...
Processing row group 103/149...
Processing row group 104/149...
Processing row group 105/149...
Processing row group 106/149...
Processing row group 107/149...
Processing row group 108/149...
Processing row group 109/149...
Processing row group 110/149...
Processing row group 111/149...
Processing row group 112/149...
Processing row group 113/149...
Processing row group 114/149...
Processing row group 115/149...
Processing row group 116/149...
Processing row group 117/149...
Processing row group 118/149...
Processing row group 119/149...
Processing row group 120/149...
Processing row group 121/149...
Processing row group 122/149...
Processing row group 123/149...
Processing row group 124/149...
Processing row group 125/149...
Processing row group 126/149...
Processing row group 127/149...
Processing row group 128/149...
Processing row group 129/149...
Processing row group 130/149...
Processing row group 131/149...
Processing row group 132/149...
Processing row group 133/149...
Processing row group 134/149...
Processing row group 135/149...
Processing row group 136/149...
Processing row group 137/149...
Processing row group 138/149...
Processing row group 139/149...
Processing row group 140/149...
Processing row group 141/149...
Processing row group 142/149...
Processing row group 143/149...
Processing row group 144/149...
Processing row group 145/149...
Processing row group 146/149...
Processing row group 147/149...
Processing row group 148/149...
Processing row group 149/149...

============================================================
STEP 3 — Verification
============================================================

Final rows       : 146,823,408
Final columns    : 30
Final row groups : 149

Remaining missing values : 0

SUCCESS — Dataset is fully ML-ready.

Saved file:
/kaggle/working/algeria_trade_master_ml_ready.parquet

File size:
5704.3 MB

In [12]:
import pyarrow.parquet as pq
import pandas as pd
import numpy as np
import gc

# ORIGINAL DATASET
orig_pf = pq.ParquetFile(MASTER)

# FINAL ML-READY DATASET
clean_pf = pq.ParquetFile(
    "/kaggle/working/algeria_trade_master_ml_ready.parquet"
)

original_missing = 0
clean_missing = 0

for i in range(orig_pf.num_row_groups):

    print(f"Checking row group {i+1}/{orig_pf.num_row_groups}...")

    orig_chunk = orig_pf.read_row_group(i).to_pandas()

    clean_chunk = clean_pf.read_row_group(i).to_pandas()

    orig_na = orig_chunk.isna().sum().sum()

    clean_na = clean_chunk.isna().sum().sum()

    original_missing += orig_na
    clean_missing += clean_na

    print(f"  Original missing : {orig_na:,}")
    print(f"  Cleaned missing  : {clean_na:,}")

    del orig_chunk, clean_chunk
    gc.collect()

filled_cells = original_missing - clean_missing

print("\n" + "="*60)
print("FINAL CLEANING SUMMARY")
print("="*60)

print(f"Original missing cells : {original_missing:,}")
print(f"Remaining missing cells: {clean_missing:,}")
print(f"Filled missing cells   : {filled_cells:,}")

if original_missing > 0:

    pct = (filled_cells / original_missing) * 100

    print(f"\nPercentage fixed       : {pct:.4f}%")

Checking row group 1/149...
  Original missing : 320,408
  Cleaned missing  : 0
Checking row group 2/149...
  Original missing : 300,872
  Cleaned missing  : 0
Checking row group 3/149...
  Original missing : 296,095
  Cleaned missing  : 0
Checking row group 4/149...
  Original missing : 338,040
  Cleaned missing  : 0
Checking row group 5/149...
  Original missing : 849,240
  Cleaned missing  : 0
Checking row group 6/149...
  Original missing : 490,077
  Cleaned missing  : 0
Checking row group 7/149...
  Original missing : 734,239
  Cleaned missing  : 0
Checking row group 8/149...
  Original missing : 242,379
  Cleaned missing  : 0
Checking row group 9/149...
  Original missing : 282,147
  Cleaned missing  : 0
Checking row group 10/149...
  Original missing : 14,161
  Cleaned missing  : 0
Checking row group 11/149...
  Original missing : 325,079
  Cleaned missing  : 0
Checking row group 12/149...
  Original missing : 298,179
  Cleaned missing  : 0
Checking row group 13/149...
  Original missing : 319,219
  Cleaned missing  : 0
Checking row group 14/149...
  Original missing : 344,077
  Cleaned missing  : 0
Checking row group 15/149...
  Original missing : 553,750
  Cleaned missing  : 0
Checking row group 16/149...
  Original missing : 821,123
  Cleaned missing  : 0
Checking row group 17/149...
  Original missing : 762,109
  Cleaned missing  : 0
Checking row group 18/149...
  Original missing : 264,801
  Cleaned missing  : 0
Checking row group 19/149...
  Original missing : 295,788
  Cleaned missing  : 0
Checking row group 20/149...
  Original missing : 52,578
  Cleaned missing  : 0
Checking row group 21/149...
  Original missing : 323,258
  Cleaned missing  : 0
Checking row group 22/149...
  Original missing : 301,784
  Cleaned missing  : 0
Checking row group 23/149...
  Original missing : 317,086
  Cleaned missing  : 0
Checking row group 24/149...
  Original missing : 326,482
  Cleaned missing  : 0
Checking row group 25/149...
  Original missing : 270,816
  Cleaned missing  : 0
Checking row group 26/149...
  Original missing : 1,119,513
  Cleaned missing  : 0
Checking row group 27/149...
  Original missing : 753,538
  Cleaned missing  : 0
Checking row group 28/149...
  Original missing : 315,431
  Cleaned missing  : 0
Checking row group 29/149...
  Original missing : 285,273
  Cleaned missing  : 0
Checking row group 30/149...
  Original missing : 137,802
  Cleaned missing  : 0
Checking row group 31/149...
  Original missing : 329,703
  Cleaned missing  : 0
Checking row group 32/149...
  Original missing : 311,424
  Cleaned missing  : 0
Checking row group 33/149...
  Original missing : 316,739
  Cleaned missing  : 0
Checking row group 34/149...
  Original missing : 310,304
  Cleaned missing  : 0
Checking row group 35/149...
  Original missing : 334,679
  Cleaned missing  : 0
Checking row group 36/149...
  Original missing : 1,109,197
  Cleaned missing  : 0
Checking row group 37/149...
  Original missing : 779,372
  Cleaned missing  : 0
Checking row group 38/149...
  Original missing : 309,245
  Cleaned missing  : 0
Checking row group 39/149...
  Original missing : 265,040
  Cleaned missing  : 0
Checking row group 40/149...
  Original missing : 221,337
  Cleaned missing  : 0
Checking row group 41/149...
  Original missing : 325,375
  Cleaned missing  : 0
Checking row group 42/149...
  Original missing : 309,387
  Cleaned missing  : 0
Checking row group 43/149...
  Original missing : 283,757
  Cleaned missing  : 0
Checking row group 44/149...
  Original missing : 303,606
  Cleaned missing  : 0
Checking row group 45/149...
  Original missing : 309,435
  Cleaned missing  : 0
Checking row group 46/149...
  Original missing : 1,103,024
  Cleaned missing  : 0
Checking row group 47/149...
  Original missing : 802,894
  Cleaned missing  : 0
Checking row group 48/149...
  Original missing : 313,620
  Cleaned missing  : 0
Checking row group 49/149...
  Original missing : 276,974
  Cleaned missing  : 0
Checking row group 50/149...
  Original missing : 218,938
  Cleaned missing  : 0
Checking row group 51/149...
  Original missing : 335,340
  Cleaned missing  : 0
Checking row group 52/149...
  Original missing : 309,960
  Cleaned missing  : 0
Checking row group 53/149...
  Original missing : 287,861
  Cleaned missing  : 0
Checking row group 54/149...
  Original missing : 359,420
  Cleaned missing  : 0
Checking row group 55/149...
  Original missing : 318,867
  Cleaned missing  : 0
Checking row group 56/149...
  Original missing : 1,113,616
  Cleaned missing  : 0
Checking row group 57/149...
  Original missing : 861,511
  Cleaned missing  : 0
Checking row group 58/149...
  Original missing : 311,409
  Cleaned missing  : 0
Checking row group 59/149...
  Original missing : 279,715
  Cleaned missing  : 0
Checking row group 60/149...
  Original missing : 340,475
  Cleaned missing  : 0
Checking row group 61/149...
  Original missing : 10,852
  Cleaned missing  : 0
Checking row group 62/149...
  Original missing : 341,731
  Cleaned missing  : 0
Checking row group 63/149...
  Original missing : 301,471
  Cleaned missing  : 0
Checking row group 64/149...
  Original missing : 306,668
  Cleaned missing  : 0
Checking row group 65/149...
  Original missing : 371,683
  Cleaned missing  : 0
Checking row group 66/149...
  Original missing : 304,445
  Cleaned missing  : 0
Checking row group 67/149...
  Original missing : 1,101,980
  Cleaned missing  : 0
Checking row group 68/149...
  Original missing : 792,640
  Cleaned missing  : 0
Checking row group 69/149...
  Original missing : 383,660
  Cleaned missing  : 0
Checking row group 70/149...
  Original missing : 295,205
  Cleaned missing  : 0
Checking row group 71/149...
  Original missing : 365,443
  Cleaned missing  : 0
Checking row group 72/149...
  Original missing : 13,635
  Cleaned missing  : 0
Checking row group 73/149...
  Original missing : 346,067
  Cleaned missing  : 0
Checking row group 74/149...
  Original missing : 319,505
  Cleaned missing  : 0
Checking row group 75/149...
  Original missing : 306,797
  Cleaned missing  : 0
Checking row group 76/149...
  Original missing : 365,913
  Cleaned missing  : 0
Checking row group 77/149...
  Original missing : 329,239
  Cleaned missing  : 0
Checking row group 78/149...
  Original missing : 1,040,912
  Cleaned missing  : 0
Checking row group 79/149...
  Original missing : 763,022
  Cleaned missing  : 0
Checking row group 80/149...
  Original missing : 563,711
  Cleaned missing  : 0
Checking row group 81/149...
  Original missing : 275,527
  Cleaned missing  : 0
Checking row group 82/149...
  Original missing : 281,745
  Cleaned missing  : 0
Checking row group 83/149...
  Original missing : 150,069
  Cleaned missing  : 0
Checking row group 84/149...
  Original missing : 350,979
  Cleaned missing  : 0
Checking row group 85/149...
  Original missing : 327,869
  Cleaned missing  : 0
Checking row group 86/149...
  Original missing : 319,211
  Cleaned missing  : 0
Checking row group 87/149...
  Original missing : 357,540
  Cleaned missing  : 0
Checking row group 88/149...
  Original missing : 339,369
  Cleaned missing  : 0
Checking row group 89/149...
  Original missing : 994,281
  Cleaned missing  : 0
Checking row group 90/149...
  Original missing : 837,018
  Cleaned missing  : 0
Checking row group 91/149...
  Original missing : 551,589
  Cleaned missing  : 0
Checking row group 92/149...
  Original missing : 302,595
  Cleaned missing  : 0
Checking row group 93/149...
  Original missing : 307,160
  Cleaned missing  : 0
Checking row group 94/149...
  Original missing : 162,871
  Cleaned missing  : 0
Checking row group 95/149...
  Original missing : 432,518
  Cleaned missing  : 0
Checking row group 96/149...
  Original missing : 470,497
  Cleaned missing  : 0
Checking row group 97/149...
  Original missing : 390,126
  Cleaned missing  : 0
Checking row group 98/149...
  Original missing : 458,847
  Cleaned missing  : 0
Checking row group 99/149...
  Original missing : 404,976
  Cleaned missing  : 0
Checking row group 100/149...
  Original missing : 1,164,031
  Cleaned missing  : 0
Checking row group 101/149...
  Original missing : 838,946
  Cleaned missing  : 0
Checking row group 102/149...
  Original missing : 615,709
  Cleaned missing  : 0
Checking row group 103/149...
  Original missing : 405,945
  Cleaned missing  : 0
Checking row group 104/149...
  Original missing : 513,762
  Cleaned missing  : 0
Checking row group 105/149...
  Original missing : 78,465
  Cleaned missing  : 0
Checking row group 106/149...
  Original missing : 400,698
  Cleaned missing  : 0
Checking row group 107/149...
  Original missing : 465,198
  Cleaned missing  : 0
Checking row group 108/149...
  Original missing : 417,367
  Cleaned missing  : 0
Checking row group 109/149...
  Original missing : 434,404
  Cleaned missing  : 0
Checking row group 110/149...
  Original missing : 432,571
  Cleaned missing  : 0
Checking row group 111/149...
  Original missing : 1,012,478
  Cleaned missing  : 0
Checking row group 112/149...
  Original missing : 482,465
  Cleaned missing  : 0
Checking row group 113/149...
  Original missing : 1,075,431
  Cleaned missing  : 0
Checking row group 114/149...
  Original missing : 403,768
  Cleaned missing  : 0
Checking row group 115/149...
  Original missing : 435,427
  Cleaned missing  : 0
Checking row group 116/149...
  Original missing : 340,895
  Cleaned missing  : 0
Checking row group 117/149...
  Original missing : 413,405
  Cleaned missing  : 0
Checking row group 118/149...
  Original missing : 471,578
  Cleaned missing  : 0
Checking row group 119/149...
  Original missing : 423,685
  Cleaned missing  : 0
Checking row group 120/149...
  Original missing : 444,776
  Cleaned missing  : 0
Checking row group 121/149...
  Original missing : 430,681
  Cleaned missing  : 0
Checking row group 122/149...
  Original missing : 1,002,780
  Cleaned missing  : 0
Checking row group 123/149...
  Original missing : 486,461
  Cleaned missing  : 0
Checking row group 124/149...
  Original missing : 1,112,203
  Cleaned missing  : 0
Checking row group 125/149...
  Original missing : 404,566
  Cleaned missing  : 0
Checking row group 126/149...
  Original missing : 442,136
  Cleaned missing  : 0
Checking row group 127/149...
  Original missing : 347,687
  Cleaned missing  : 0
Checking row group 128/149...
  Original missing : 432,896
  Cleaned missing  : 0
Checking row group 129/149...
  Original missing : 495,354
  Cleaned missing  : 0
Checking row group 130/149...
  Original missing : 458,575
  Cleaned missing  : 0
Checking row group 131/149...
  Original missing : 433,720
  Cleaned missing  : 0
Checking row group 132/149...
  Original missing : 450,689
  Cleaned missing  : 0
Checking row group 133/149...
  Original missing : 1,028,560
  Cleaned missing  : 0
Checking row group 134/149...
  Original missing : 471,693
  Cleaned missing  : 0
Checking row group 135/149...
  Original missing : 1,142,665
  Cleaned missing  : 0
Checking row group 136/149...
  Original missing : 433,712
  Cleaned missing  : 0
Checking row group 137/149...
  Original missing : 469,026
  Cleaned missing  : 0
Checking row group 138/149...
  Original missing : 373,488
  Cleaned missing  : 0
Checking row group 139/149...
  Original missing : 471,887
  Cleaned missing  : 0
Checking row group 140/149...
  Original missing : 538,931
  Cleaned missing  : 0
Checking row group 141/149...
  Original missing : 470,809
  Cleaned missing  : 0
Checking row group 142/149...
  Original missing : 470,160
  Cleaned missing  : 0
Checking row group 143/149...
  Original missing : 445,966
  Cleaned missing  : 0
Checking row group 144/149...
  Original missing : 1,104,425
  Cleaned missing  : 0
Checking row group 145/149...
  Original missing : 882,433
  Cleaned missing  : 0
Checking row group 146/149...
  Original missing : 735,067
  Cleaned missing  : 0
Checking row group 147/149...
  Original missing : 438,585
  Cleaned missing  : 0
Checking row group 148/149...
  Original missing : 592,058
  Cleaned missing  : 0
Checking row group 149/149...
  Original missing : 41,677
  Cleaned missing  : 0

============================================================
FINAL CLEANING SUMMARY
============================================================
Original missing cells : 69,326,828
Remaining missing cells: 0
Filled missing cells   : 69,326,828

Percentage fixed       : 100.0000%